// AUTO-GENERATED by scripts/build-guides.mjs — do not edit by hand.
export interface GuideCatalogEntry { slug: string; title: string; subtitle: string; lede: string; }
export const GUIDE_CATALOG: GuideCatalogEntry[] = [
  {
    "slug": "better-sleep",
    "title": "How to Sleep Better, Naturally",
    "subtitle": "My Longevity Hub guide",
    "lede": "Most sleep problems are fixed by a handful of daytime habits — long before you need anything from a bottle. Here's what works, and where supplements genuinely fit."
  },
  {
    "slug": "why-am-i-always-tired",
    "title": "Why Am I Always Tired? How to Get Your Energy Back",
    "subtitle": "My Longevity Hub guide",
    "lede": "Energy is what's left once your body has covered sleep, stress, food and movement. Here's how to find the leaks — and where nutrients, and NAD+, genuinely fit."
  },
  {
    "slug": "what-supplements-to-take",
    "title": "What Supplements Should You Actually Take?",
    "subtitle": "My Longevity Hub guide",
    "lede": "Most of the supplement wall is money you don't need to spend — but a small handful genuinely fill common gaps. Here's the honest short list."
  },
  {
    "slug": "skincare",
    "title": "Skincare That Actually Works: An Evidence-Based Guide",
    "subtitle": "My Longevity Hub guide",
    "lede": "A handful of well-evidenced basics do almost all the work for healthy, resilient skin. Here's what genuinely helps — and an honest look at where peptides fit."
  },
  {
    "slug": "hair-loss",
    "title": "Hair Loss and Hair Growth: What Actually Works",
    "subtitle": "My Longevity Hub guide",
    "lede": "A couple of treatments are genuinely proven, some nutrition helps if you're deficient, and a lot of what's sold is wishful thinking. Here's the straight version."
  },
  {
    "slug": "testosterone",
    "title": "Low Testosterone: Signs, Causes and What Actually Helps",
    "subtitle": "My Longevity Hub guide",
    "lede": "Low testosterone is real — but also over-diagnosed by marketing. Here's the honest picture: the signs, what genuinely affects your levels, and what actually helps."
  },
  {
    "slug": "menopause",
    "title": "Menopause and Perimenopause: Symptoms, HRT and Real Support",
    "subtitle": "My Longevity Hub guide",
    "lede": "Menopause is a normal life stage — but you don't have to just grit your teeth through it. Here's what's happening, and what genuinely helps."
  },
  {
    "slug": "injury-recovery",
    "title": "Injury Recovery: How to Heal Faster",
    "subtitle": "My Longevity Hub guide",
    "lede": "Time plus smart loading does most of the healing — and a few basics genuinely speed it up. Here's what works, plus an honest look at the peptides people ask about."
  },
  {
    "slug": "muscle-growth",
    "title": "Building Muscle and Recovering from Training",
    "subtitle": "My Longevity Hub guide",
    "lede": "Muscle comes down to progressively harder training, enough protein, and real recovery. No supplement or peptide out-runs those three — here's the honest hierarchy."
  },
  {
    "slug": "gut-health",
    "title": "Gut Health Basics: What Actually Helps",
    "subtitle": "My Longevity Hub guide",
    "lede": "The gut-health basics are refreshingly simple and genuinely powerful. Here's what actually helps your microbiome — and an honest note on the peptides people ask about."
  },
  {
    "slug": "peptides-101",
    "title": "Research Peptides 101: What They Are, Safety and UK Law",
    "subtitle": "My Longevity Hub guide",
    "lede": "Peptides are one of the most hyped and misunderstood topics in health. Here's the no-spin primer: what they are, what 'research use only' means, and where UK law and the evidence actually stand."
  },
  {
    "slug": "longevity-basics",
    "title": "Living Longer: The Habits That Actually Work",
    "subtitle": "My Longevity Hub guide",
    "lede": "The biggest longevity wins are the basics done consistently for decades. The research frontier is real too — but it's the icing, not the cake. Here's how to think about both."
  },
  {
    "slug": "weight-loss",
    "title": "Losing Fat and Keeping It Off: A No-Hype Guide",
    "subtitle": "My Longevity Hub guide",
    "lede": "Fat loss is the most over-promised topic in health. The honest version is simpler than the industry wants you to believe: a sustainable deficit you can actually live with."
  },
  {
    "slug": "stress-focus",
    "title": "Stress, Mood and Focus: Calming the Noise",
    "subtitle": "My Longevity Hub guide",
    "lede": "Stress, low mood and brain fog often share the same roots — and the same fixes. Here's what genuinely helps day to day, and the line where it's time to get support."
  },
  {
    "slug": "immunity",
    "title": "Supporting Your Immune System: What Actually Helps",
    "subtitle": "My Longevity Hub guide",
    "lede": "You can't crank your immune system up like a dial — but you can support it to work as well as it should, and stop dragging it down. Here's the honest version."
  }
];
const TITLES: Record<string, string> = Object.fromEntries(GUIDE_CATALOG.map((g) => [g.slug, g.title]));
export function guideTitle(slug: string): string | undefined { return TITLES[slug]; }
