// AUTO-GENERATED by scripts/build-guides.mjs — do not edit by hand.
export const guide = {
  slug: "hair-loss",
  title: "Hair Loss and Hair Growth: What Actually Works",
  lede: "A couple of treatments are genuinely proven, some nutrition helps if you're deficient, and a lot of what's sold is wishful thinking. Here's the straight version.",
  meta: {
    title: "Hair Loss and Hair Growth: What Actually Works | My Longevity Hub",
    description: "An honest guide to hair loss and regrowth — why hair thins, the proven treatments (minoxidil, finasteride), nutrition that helps, what's overhyped, and where peptide research fits.",
    keywords: "hair loss, hair growth, how to stop hair loss, minoxidil, finasteride, biotin for hair, thinning hair, GHK-Cu hair",
  },
  ldJson: `{"@context": "https://schema.org", "@graph": [{"@type": "Article", "headline": "Hair Loss and Hair Growth: What Actually Works", "description": "An honest guide to hair loss and regrowth \\u2014 why hair thins, the proven treatments (minoxidil, finasteride), nutrition that helps, what's overhyped, and where peptide research fits.", "author": {"@type": "Organization", "name": "My Longevity Hub"}, "publisher": {"@type": "Organization", "name": "My Longevity Hub"}, "dateModified": "2026-09-04"}, {"@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": "What actually stops hair loss?", "acceptedAnswer": {"@type": "Answer", "text": "The two treatments with the strongest evidence are minoxidil (topical, over the counter) and, for men, finasteride (a prescription tablet that blocks DHT). Both need ongoing use and are worth discussing with a pharmacist or GP."}}, {"@type": "Question", "name": "Does biotin help hair growth?", "acceptedAnswer": {"@type": "Answer", "text": "Biotin only helps the small number of people who are genuinely deficient. For everyone else, the marketing far outstrips the evidence. Checking iron, thyroid and protein intake is usually more useful."}}, {"@type": "Question", "name": "Can peptides regrow hair?", "acceptedAnswer": {"@type": "Answer", "text": "Copper peptides such as GHK-Cu are an area of research interest for hair and scalp, but research-grade GHK-Cu is sold for laboratory research use only \\u2014 not as a hair treatment and not for human use. Proven options like minoxidil come first."}}, {"@type": "Question", "name": "When should I see a doctor about hair loss?", "acceptedAnswer": {"@type": "Answer", "text": "See a GP for sudden, patchy or rapid loss, loss alongside other symptoms like fatigue or weight change, or if it's affecting your wellbeing. Several causes are very treatable once diagnosed."}}]}]}`,
  html: `<main>
  <div class="kicker">Guide</div>
  <h1>Hair Loss and Hair Growth: What Actually Works</h1>
  <p class="byline">By the My Longevity Hub editorial team · Updated September 2026 · 3 min read</p>
  <p class="lede">A couple of treatments are genuinely proven, some nutrition helps if you're deficient, and a lot of what's sold is wishful thinking. Here's the straight version.</p>
  
<div class="toc"><div>On this page</div>
  <a href="#why">Why hair thins</a>
  <a href="#works">What actually works</a>
  <a href="#nutrition">Nutrition for your hair</a>
  <a href="#peptides">The peptide research angle</a>
  <a href="#overhyped">What's overhyped</a>
  <a href="#doctor">When to see a doctor</a>
</div>

<p>Hair loss is extremely common and rarely talked about honestly. The good news is that a couple of treatments are
genuinely proven, some nutrition tweaks help if you're deficient, and a lot of what's sold is wishful thinking. Here's
the straight version.</p>

<h2 id="why">Why hair thins</h2>
<ul>
  <li><strong>Pattern hair loss (androgenetic alopecia)</strong> — the most common cause in both men and women, largely
  genetic and driven by the hormone DHT. It's gradual: a receding hairline or thinning crown in men, widening parting
  in women.</li>
  <li><strong>Telogen effluvium</strong> — temporary shedding a few months after stress, illness, surgery, childbirth
  or rapid weight loss. It usually recovers.</li>
  <li><strong>Nutrient and health issues</strong> — low iron (ferritin), thyroid problems, and crash dieting can all
  thin hair.</li>
</ul>

<h2 id="works">What actually works</h2>
<p>Two treatments have the strongest evidence, and both are worth a proper conversation with a pharmacist or GP:</p>
<ul>
  <li><strong>Minoxidil</strong> <span class="tier">Strong</span> — a topical (and now sometimes oral) treatment
  available over the counter that can slow loss and regrow some hair. It needs consistent, ongoing use to keep the
  benefit.</li>
  <li><strong>Finasteride</strong> <span class="tier">Strong</span> — a prescription tablet for men that blocks DHT
  and is effective for pattern loss. Because it's a prescription-only medicine in the UK, it needs a doctor, who'll
  talk you through the benefits and possible side effects.</li>
</ul>
<p>For women, minoxidil plus treating any underlying cause (iron, thyroid) is the usual evidence-based route — a GP
can guide this.</p>

<h2 id="nutrition">Nutrition for your hair</h2>
<p>The rule here is the same as everywhere: <strong>fix a genuine deficiency and it helps; top up what you already
have and it usually won't.</strong> Worth checking: iron/ferritin (a common, correctable cause of shedding), vitamin D,
and enough protein. <strong>Biotin</strong> is heavily marketed for hair, but only actually helps the rare people who
are deficient. See our <a href="/guides/what-supplements-to-take">supplements guide</a> for choosing well.</p>

<h2 id="peptides">The peptide research angle</h2>
<p>Peptides are an active research area for skin and hair. <strong>GHK-Cu (copper peptide)</strong> in particular has
drawn scientific interest for follicle and scalp-related pathways.</p>
<div class="callout"><strong>Important:</strong> research-grade GHK-Cu is sold <strong>for laboratory research use
only</strong> — it is not a hair treatment, not a cosmetic, and not for human use. The proven options above are where
to start if you actually want to keep your hair.</div>

<h2 id="overhyped">What's overhyped</h2>
<p>Most "hair growth" gummies, biotin megadoses (if you're not deficient), and thickening serums promise far more than
the evidence supports. Save your money for what works.</p>

<h2 id="doctor">When to see a doctor</h2>
<p>See a GP for <strong>sudden, patchy or rapid hair loss</strong>, loss with other symptoms (fatigue, weight change),
or if it's affecting your confidence — some causes are very treatable, and getting the diagnosis right matters.</p>

  
    <aside class="funnel">
      <div class="funnel-k">Where to look</div>
      <p>Copper peptides (GHK-Cu) are an area of active hair and skin research. My Peptides supplies research-grade GHK-Cu strictly for laboratory research use only — for those reading into the science, not for personal use. For proven treatments, speak to a pharmacist or GP.</p>
      <a class="funnel-cta" href="https://my-peptides.co.uk/products/ghk-cu" target="_blank" rel="noopener">Explore the GHK-Cu research →</a>
    </aside>
  <div class="faqwrap"><h2>Frequently asked questions</h2><div class="faq"><h3>What actually stops hair loss?</h3><p>The two treatments with the strongest evidence are minoxidil (topical, over the counter) and, for men, finasteride (a prescription tablet that blocks DHT). Both need ongoing use and are worth discussing with a pharmacist or GP.</p></div><div class="faq"><h3>Does biotin help hair growth?</h3><p>Biotin only helps the small number of people who are genuinely deficient. For everyone else, the marketing far outstrips the evidence. Checking iron, thyroid and protein intake is usually more useful.</p></div><div class="faq"><h3>Can peptides regrow hair?</h3><p>Copper peptides such as GHK-Cu are an area of research interest for hair and scalp, but research-grade GHK-Cu is sold for laboratory research use only — not as a hair treatment and not for human use. Proven options like minoxidil come first.</p></div><div class="faq"><h3>When should I see a doctor about hair loss?</h3><p>See a GP for sudden, patchy or rapid loss, loss alongside other symptoms like fatigue or weight change, or if it's affecting your wellbeing. Several causes are very treatable once diagnosed.</p></div></div>
  <div class="refs"><h2>Sources &amp; further reading</h2><ol><li><a href="https://www.nhs.uk/conditions/hair-loss/" target="_blank" rel="noopener nofollow">NHS — Hair loss</a></li><li><a href="https://www.aad.org/public/diseases/hair-loss" target="_blank" rel="noopener nofollow">American Academy of Dermatology — Hair loss: who gets and causes</a></li><li><a href="https://my.clevelandclinic.org/health/diseases/16921-hair-loss" target="_blank" rel="noopener nofollow">Cleveland Clinic — Hair loss (alopecia)</a></li><li><a href="https://www.mayoclinic.org/diseases-conditions/hair-loss/diagnosis-treatment/drc-20372932" target="_blank" rel="noopener nofollow">Mayo Clinic — Hair loss diagnosis and treatment</a></li><li><a href="https://examine.com/supplements/biotin/" target="_blank" rel="noopener nofollow">Examine.com — Biotin</a></li></ol></div>
</main>
<footer class="disc">
  <strong>General information only.</strong> This guide is educational and is not medical advice, diagnosis or treatment.
  It doesn't replace a conversation with your GP, pharmacist or a qualified clinician — especially if you're pregnant,
  breastfeeding, taking medication or managing a health condition. For anything urgent, call <strong>999</strong> or NHS <strong>111</strong>.
  Research peptides referenced here are sold for laboratory research use only and are not for human or animal consumption.
</footer>`,
} as const;
