// AUTO-GENERATED by scripts/build-guides.mjs — do not edit by hand.
export const guide = {
  slug: "immunity",
  title: "Supporting Your Immune System: What Actually Helps",
  lede: "You can't crank your immune system up like a dial — but you can support it to work as well as it should, and stop dragging it down. Here's the honest version.",
  meta: {
    title: "Supporting Your Immune System: What Actually Helps | My Longevity Hub",
    description: "An honest guide to immune health — why you can't simply 'boost' immunity, the foundations that make it resilient, the nutrients that genuinely support it (vitamin D, C, zinc), and what's overhyped.",
    keywords: "immune system, immunity, how to boost immune system, immune support, vitamin d immunity, vitamin c, zinc, getting sick often",
  },
  ldJson: `{"@context": "https://schema.org", "@graph": [{"@type": "Article", "headline": "Supporting Your Immune System: What Actually Helps", "description": "An honest guide to immune health \\u2014 why you can't simply 'boost' immunity, the foundations that make it resilient, the nutrients that genuinely support it (vitamin D, C, zinc), and what's overhyped.", "author": {"@type": "Organization", "name": "My Longevity Hub"}, "publisher": {"@type": "Organization", "name": "My Longevity Hub"}, "dateModified": "2026-09-04"}, {"@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": "Can you actually boost your immune system?", "acceptedAnswer": {"@type": "Answer", "text": "Not in the way marketing implies. A healthy immune system doesn't need boosting so much as balancing and supporting \\u2014 giving it what it needs (sleep, good food, movement, low stress) and removing what undermines it."}}, {"@type": "Question", "name": "What supplements help immunity?", "acceptedAnswer": {"@type": "Answer", "text": "Vitamin D, vitamin C and zinc all contribute to normal immune function, and are most useful if you're actually short of them. Vitamin D is worth considering in the UK winter. High doses aren't better and some can backfire."}}, {"@type": "Question", "name": "Does vitamin C stop colds?", "acceptedAnswer": {"@type": "Answer", "text": "It won't prevent colds for most people, though it may slightly shorten them for some. It contributes to normal immune function as part of a good diet rather than acting as a cure."}}, {"@type": "Question", "name": "Why do I keep getting sick?", "acceptedAnswer": {"@type": "Answer", "text": "Often it's down to run-down basics \\u2014 poor sleep, high stress, a patchy diet. But frequent, severe or unusually persistent infections that don't clear as expected are worth seeing a GP about."}}]}]}`,
  html: `<main>
  <div class="kicker">Guide</div>
  <h1>Supporting Your Immune System: What Actually Helps</h1>
  <p class="byline">By the My Longevity Hub editorial team · Updated September 2026 · 3 min read</p>
  <p class="lede">You can't crank your immune system up like a dial — but you can support it to work as well as it should, and stop dragging it down. Here's the honest version.</p>
  
<div class="toc"><div>On this page</div>
  <a href="#truth">Can you really "boost" your immune system?</a>
  <a href="#foundations">The foundations of a resilient immune system</a>
  <a href="#supplements">Supplements that genuinely support immunity</a>
  <a href="#hype">What's overhyped</a>
  <a href="#doctor">When to see a doctor</a>
</div>

<p>Every winter the "immune boosting" products come out in force. The honest science is less dramatic but more useful:
you can't crank your immune system up like a dial, but you can support it so it works as well as it should — and avoid
the things that drag it down.</p>

<h2 id="truth">Can you really "boost" your immune system?</h2>
<p>Not in the way the marketing implies. A healthy immune system isn't "low" and in need of boosting — it needs to be
balanced and well-supported. The goal is to give it what it needs and remove what undermines it, not to super-charge it.</p>

<h2 id="foundations">The foundations of a resilient immune system</h2>
<ul>
  <li><strong>Sleep.</strong> Consistently short sleep measurably weakens immune defences (our
  <a href="/guides/better-sleep">sleep guide</a>).</li>
  <li><strong>A varied, mostly-plant diet.</strong> A wide range of nutrients and fibre supports both immunity and gut
  health (our <a href="/guides/gut-health">gut guide</a>).</li>
  <li><strong>Regular movement</strong> and not smoking.</li>
  <li><strong>Manage stress</strong> — chronic stress suppresses immune function.</li>
  <li><strong>Good hygiene and staying up to date with recommended vaccinations.</strong></li>
</ul>

<h2 id="supplements">Supplements that genuinely support immunity</h2>
<p>A few nutrients have authorised roles in normal immune function — most useful when you're actually short of them:</p>
<ul>
  <li><strong>Vitamin D</strong> <span class="tier">Moderate</span> — contributes to normal immune function, and many
  people in the UK are low in winter; the NHS suggests considering 10 micrograms daily over the darker months.</li>
  <li><strong>Vitamin C</strong> <span class="tier">Moderate</span> — contributes to normal immune function; won't
  prevent colds but may slightly shorten them for some.</li>
  <li><strong>Zinc</strong> <span class="tier">Moderate</span> — contributes to normal immune function; useful mainly
  if you're low, and high doses aren't better.</li>
</ul>
<p>See our <a href="/guides/what-supplements-to-take">supplements guide</a> for choosing well.</p>

<h2 id="hype">What's overhyped</h2>
<p>Mega-dose "immune boosters", most exotic mushroom blends and high-dose antioxidant stacks promise far more than the
evidence supports — and very high doses of some nutrients can be counterproductive. The basics beat the hype.</p>

<h2 id="doctor">When to see a doctor</h2>
<p>See your GP if you get <strong>frequent, severe or unusually persistent infections</strong>, or infections that
don't clear as expected — this can occasionally signal an underlying issue worth checking.</p>

  
    <aside class="funnel">
      <div class="funnel-k">Where to look</div>
      <p>For the nutrients that support normal immune function — vitamin D, vitamin C and zinc — My Longevity Hub partners with imnatura. They work best alongside the real foundations: sleep, good food and managing stress.</p>
      <a class="funnel-cta" href="https://imnatura.co.uk" target="_blank" rel="noopener">Browse imnatura supplements →</a>
    </aside>
  <div class="faqwrap"><h2>Frequently asked questions</h2><div class="faq"><h3>Can you actually boost your immune system?</h3><p>Not in the way marketing implies. A healthy immune system doesn't need boosting so much as balancing and supporting — giving it what it needs (sleep, good food, movement, low stress) and removing what undermines it.</p></div><div class="faq"><h3>What supplements help immunity?</h3><p>Vitamin D, vitamin C and zinc all contribute to normal immune function, and are most useful if you're actually short of them. Vitamin D is worth considering in the UK winter. High doses aren't better and some can backfire.</p></div><div class="faq"><h3>Does vitamin C stop colds?</h3><p>It won't prevent colds for most people, though it may slightly shorten them for some. It contributes to normal immune function as part of a good diet rather than acting as a cure.</p></div><div class="faq"><h3>Why do I keep getting sick?</h3><p>Often it's down to run-down basics — poor sleep, high stress, a patchy diet. But frequent, severe or unusually persistent infections that don't clear as expected are worth seeing a GP about.</p></div></div>
  <div class="refs"><h2>Sources &amp; further reading</h2><ol><li><a href="https://www.nhs.uk/live-well/eat-well/" target="_blank" rel="noopener nofollow">NHS — How to have a healthy immune system</a></li><li><a href="https://www.hsph.harvard.edu/nutritionsource/nutrition-and-immunity/" target="_blank" rel="noopener nofollow">Harvard T.H. Chan School of Public Health — Nutrition and immunity</a></li><li><a href="https://health.clevelandclinic.org/how-to-boost-your-immune-system" target="_blank" rel="noopener nofollow">Cleveland Clinic — How to boost your immune system</a></li><li><a href="https://www.mayoclinic.org/diseases-conditions/coronavirus/in-depth/coronavirus-immune-system/art-20487056" target="_blank" rel="noopener nofollow">Mayo Clinic — Support your immune system</a></li><li><a href="https://examine.com/supplements/zinc/" target="_blank" rel="noopener nofollow">Examine.com — Zinc</a></li></ol></div>
</main>
<footer class="disc">
  <strong>General information only.</strong> This guide is educational and is not medical advice, diagnosis or treatment.
  It doesn't replace a conversation with your GP, pharmacist or a qualified clinician — especially if you're pregnant,
  breastfeeding, taking medication or managing a health condition. For anything urgent, call <strong>999</strong> or NHS <strong>111</strong>.
  Food supplements are not a substitute for a varied diet and a healthy lifestyle.
</footer>`,
} as const;
