// AUTO-GENERATED by scripts/build-guides.mjs — do not edit by hand.
import { guide as g0 } from "./better-sleep";
import { guide as g1 } from "./why-am-i-always-tired";
import { guide as g2 } from "./what-supplements-to-take";
import { guide as g3 } from "./skincare";
import { guide as g4 } from "./hair-loss";
import { guide as g5 } from "./testosterone";
import { guide as g6 } from "./menopause";
import { guide as g7 } from "./injury-recovery";
import { guide as g8 } from "./muscle-growth";
import { guide as g9 } from "./gut-health";
import { guide as g10 } from "./peptides-101";
import { guide as g11 } from "./longevity-basics";
import { guide as g12 } from "./weight-loss";
import { guide as g13 } from "./stress-focus";
import { guide as g14 } from "./immunity";

export const GUIDES = [g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14] as const;
export type Guide = (typeof GUIDES)[number];
export const BY_SLUG: Record<string, Guide> =
  Object.fromEntries(GUIDES.map((g) => [g.slug, g]));
