// AUTO-GENERATED by scripts/build-guides.mjs — do not edit by hand.
export const guide = {
  slug: "injury-recovery",
  title: "Injury Recovery: How to Heal Faster",
  lede: "Time plus smart loading does most of the healing — and a few basics genuinely speed it up. Here's what works, plus an honest look at the peptides people ask about.",
  meta: {
    title: "Injury Recovery: How to Heal Faster | My Longevity Hub",
    description: "An honest guide to recovering from injury — the foundations that actually speed healing, the nutrition that helps, and a clear-eyed look at recovery peptides like BPC-157 and TB-500.",
    keywords: "injury recovery, how to heal faster, tendon healing, BPC-157, TB-500, soft tissue recovery, muscle strain recovery",
  },
  ldJson: `{"@context": "https://schema.org", "@graph": [{"@type": "Article", "headline": "Injury Recovery: How to Heal Faster", "description": "An honest guide to recovering from injury \\u2014 the foundations that actually speed healing, the nutrition that helps, and a clear-eyed look at recovery peptides like BPC-157 and TB-500.", "author": {"@type": "Organization", "name": "My Longevity Hub"}, "publisher": {"@type": "Organization", "name": "My Longevity Hub"}, "dateModified": "2026-09-04"}, {"@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": "How can I heal an injury faster?", "acceptedAnswer": {"@type": "Answer", "text": "Prioritise relative rest with gentle progressive loading (ideally guided by a physio), protect your sleep, eat enough protein, and don't smoke. These foundations do most of the work; rehab consistency beats any shortcut."}}, {"@type": "Question", "name": "Does BPC-157 work for tendon injuries?", "acceptedAnswer": {"@type": "Answer", "text": "BPC-157 has generated real scientific interest for soft-tissue and tendon healing, but the strong results are largely from animal studies \\u2014 robust human trials are still lacking. It's sold for laboratory research use only and is not approved for human use."}}, {"@type": "Question", "name": "What supplements help recovery?", "acceptedAnswer": {"@type": "Answer", "text": "Enough protein is the big one, plus vitamin C (for collagen), vitamin D, and possibly collagen peptides, omega-3 and creatine. They support the foundations rather than replacing rehab."}}, {"@type": "Question", "name": "When should I see a physio or doctor about an injury?", "acceptedAnswer": {"@type": "Answer", "text": "See a professional for severe pain, an injury not improving after a couple of weeks, or one with significant swelling, instability, numbness or inability to bear weight."}}]}]}`,
  html: `<main>
  <div class="kicker">Guide</div>
  <h1>Injury Recovery: How to Heal Faster</h1>
  <p class="byline">By the My Longevity Hub editorial team · Updated September 2026 · 3 min read</p>
  <p class="lede">Time plus smart loading does most of the healing — and a few basics genuinely speed it up. Here's what works, plus an honest look at the peptides people ask about.</p>
  
<div class="toc"><div>On this page</div>
  <a href="#foundations">The foundations of healing</a>
  <a href="#nutrition">Nutrition and supplements for recovery</a>
  <a href="#peptides">The peptide research frontier</a>
  <a href="#mistakes">Common recovery mistakes</a>
  <a href="#doctor">When to see a professional</a>
</div>

<p>Whether it's a tweaked tendon, a strained muscle or a joint that won't settle, the honest truth about recovery is
that <strong>time plus smart loading</strong> does most of the work — and a few basics genuinely speed it along. Here's
what helps, plus a clear-eyed look at the peptides people ask about.</p>

<h2 id="foundations">The foundations of healing</h2>
<ul>
  <li><strong>Relative rest, not total rest.</strong> Complete rest often weakens tissue; gentle, progressive movement
  within comfort usually helps most injuries heal stronger. A physiotherapist can guide the right loading.</li>
  <li><strong>Progressive loading and rehab.</strong> Tendons and muscles adapt to gradual, controlled stress — this is
  the single most effective driver of recovery for most soft-tissue injuries.</li>
  <li><strong>Sleep.</strong> Repair happens largely while you sleep; protect it (see our
  <a href="/guides/better-sleep">sleep guide</a>).</li>
  <li><strong>Enough protein and overall nutrition.</strong> Healing tissue needs building blocks and energy — don't
  under-eat while injured.</li>
  <li><strong>Don't smoke</strong>, and keep alcohol modest — both slow healing.</li>
</ul>

<h2 id="nutrition">Nutrition and supplements for recovery</h2>
<ul>
  <li><strong>Protein</strong> <span class="tier">Strong</span> — the raw material for repair; spread it across the day.</li>
  <li><strong>Vitamin C</strong> <span class="tier">Moderate</span> — needed for collagen synthesis.</li>
  <li><strong>Vitamin D</strong> <span class="tier">Moderate</span> — supports bone and muscle; worth not being deficient in.</li>
  <li><strong>Collagen peptides</strong> <span class="tier">Promising</span> — some evidence for tendon and joint support.</li>
  <li><strong>Omega-3 and creatine</strong> <span class="tier">Promising</span> — may support recovery and help maintain
  muscle while you're less active.</li>
</ul>
<p>Our <a href="/guides/what-supplements-to-take">supplements guide</a> covers how to choose these well.</p>

<h2 id="peptides">The peptide research frontier</h2>
<p>Two research peptides come up constantly in recovery conversations: <strong>BPC-157</strong> and <strong>TB-500</strong>.
Both have generated real scientific interest for soft-tissue, tendon and wound-healing pathways — but it's important to
be honest about where the evidence actually is.</p>
<ul>
  <li><strong>BPC-157</strong> <span class="tier">Animal-only</span> — striking results in animal studies; robust human
  clinical trials are still lacking.</li>
  <li><strong>TB-500 (thymosin beta-4)</strong> <span class="tier">Animal-only</span> — similar picture: interesting
  preclinical research, limited human data.</li>
</ul>
<div class="callout"><strong>Important:</strong> these are sold <strong>for laboratory research use only</strong> — they
are not licensed medicines, not approved for human use, and this guide is not telling anyone to take them. Treat them as
science to read about, and rely on the proven foundations above to actually recover.</div>

<h2 id="mistakes">Common recovery mistakes</h2>
<p>Resting too completely, returning to full load too soon, chasing passive treatments while skipping rehab exercises,
and under-eating are the classics. Consistency with rehab beats any shortcut.</p>

<h2 id="doctor">When to see a professional</h2>
<p>See a physiotherapist or GP for pain that's severe, not improving after a couple of weeks, or accompanied by
significant swelling, instability, numbness or inability to bear weight — getting the diagnosis and rehab right is what
actually gets you back.</p>

  
    <aside class="funnel">
      <div class="funnel-k">Where to look</div>
      <p>BPC-157 and TB-500 are among the most-discussed peptides in soft-tissue recovery research. My Peptides supplies them strictly for laboratory research use only — a resource for those reading into the science, not for personal use. For an actual injury, start with a physio and the foundations above.</p>
      <a class="funnel-cta" href="https://my-peptides.co.uk/products/bpc-157" target="_blank" rel="noopener">Explore the BPC-157 research →</a>
    </aside>
  <div class="faqwrap"><h2>Frequently asked questions</h2><div class="faq"><h3>How can I heal an injury faster?</h3><p>Prioritise relative rest with gentle progressive loading (ideally guided by a physio), protect your sleep, eat enough protein, and don't smoke. These foundations do most of the work; rehab consistency beats any shortcut.</p></div><div class="faq"><h3>Does BPC-157 work for tendon injuries?</h3><p>BPC-157 has generated real scientific interest for soft-tissue and tendon healing, but the strong results are largely from animal studies — robust human trials are still lacking. It's sold for laboratory research use only and is not approved for human use.</p></div><div class="faq"><h3>What supplements help recovery?</h3><p>Enough protein is the big one, plus vitamin C (for collagen), vitamin D, and possibly collagen peptides, omega-3 and creatine. They support the foundations rather than replacing rehab.</p></div><div class="faq"><h3>When should I see a physio or doctor about an injury?</h3><p>See a professional for severe pain, an injury not improving after a couple of weeks, or one with significant swelling, instability, numbness or inability to bear weight.</p></div></div>
  <div class="refs"><h2>Sources &amp; further reading</h2><ol><li><a href="https://www.nhs.uk/conditions/sprains-and-strains/" target="_blank" rel="noopener nofollow">NHS — Sprains and strains</a></li><li><a href="https://my.clevelandclinic.org/health/diseases/22289-tendinopathy" target="_blank" rel="noopener nofollow">Cleveland Clinic — Tendinopathy</a></li><li><a href="https://www.mayoclinic.org/diseases-conditions/sprains/diagnosis-treatment/drc-20377943" target="_blank" rel="noopener nofollow">Mayo Clinic — Sprains: diagnosis and treatment</a></li><li><a href="https://examine.com/supplements/collagen/" target="_blank" rel="noopener nofollow">Examine.com — Collagen for joints</a></li><li><a href="https://examine.com/supplements/bpc-157/" target="_blank" rel="noopener nofollow">Examine.com — BPC-157</a></li></ol></div>
</main>
<footer class="disc">
  <strong>General information only.</strong> This guide is educational and is not medical advice, diagnosis or treatment.
  It doesn't replace a conversation with your GP, physiotherapist, pharmacist or a qualified clinician — especially if
  you're pregnant, breastfeeding, taking medication or managing a health condition. For anything urgent, call
  <strong>999</strong> or NHS <strong>111</strong>. Research peptides referenced here are sold for laboratory research
  use only and are not for human or animal consumption.
</footer>`,
} as const;
