// AUTO-GENERATED by scripts/build-guides.mjs — do not edit by hand.
export const guide = {
  slug: "longevity-basics",
  title: "Living Longer: The Habits That Actually Work",
  lede: "The biggest longevity wins are the basics done consistently for decades. The research frontier is real too — but it's the icing, not the cake. Here's how to think about both.",
  meta: {
    title: "Living Longer: The Habits That Actually Work | My Longevity Hub",
    description: "An honest longevity guide — the evidence-based habits that genuinely extend healthy life, the supplements with a real ageing angle, the NAD+ story, and how to cut through the hype.",
    keywords: "how to live longer, longevity, healthy ageing, healthspan, anti-aging, NAD, longevity supplements",
  },
  ldJson: `{"@context": "https://schema.org", "@graph": [{"@type": "Article", "headline": "Living Longer: The Habits That Actually Work", "description": "An honest longevity guide \\u2014 the evidence-based habits that genuinely extend healthy life, the supplements with a real ageing angle, the NAD+ story, and how to cut through the hype.", "author": {"@type": "Organization", "name": "My Longevity Hub"}, "publisher": {"@type": "Organization", "name": "My Longevity Hub"}, "dateModified": "2026-09-04"}, {"@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": "What actually helps you live longer?", "acceptedAnswer": {"@type": "Answer", "text": "The strongest levers are not smoking, staying active and keeping muscle, eating mostly whole foods, protecting sleep, keeping alcohol modest, managing stress, and staying socially connected. These matter far more than any supplement."}}, {"@type": "Question", "name": "Do longevity supplements work?", "acceptedAnswer": {"@type": "Answer", "text": "No supplement replaces the lifestyle basics, but vitamin D, omega-3 and creatine have reasonable evidence for healthy ageing. Be sceptical of anything promising to 'reverse ageing'."}}, {"@type": "Question", "name": "Does NAD+ help with ageing?", "acceptedAnswer": {"@type": "Answer", "text": "NAD+ is a coenzyme central to energy and repair that declines with age. Precursors can raise NAD+ levels in humans and the healthy-ageing research is promising, but it's an emerging field rather than a proven anti-ageing cure."}}]}]}`,
  html: `<main>
  <div class="kicker">Guide</div>
  <h1>Living Longer: The Habits That Actually Work</h1>
  <p class="byline">By the My Longevity Hub editorial team · Updated September 2026 · 3 min read</p>
  <p class="lede">The biggest longevity wins are the basics done consistently for decades. The research frontier is real too — but it's the icing, not the cake. Here's how to think about both.</p>
  
<div class="toc"><div>On this page</div>
  <a href="#levers">The levers that actually move the needle</a>
  <a href="#supplements">Supplements with a longevity angle</a>
  <a href="#nad">NAD+ and cellular ageing</a>
  <a href="#hype">Cutting through the hype</a>
</div>

<p>"How do I live longer?" is the question behind half of everything on this site. The honest, slightly boring answer:
the biggest wins are the basics done consistently for decades. The exciting research frontier is real too — but it's
the icing, not the cake. Here's how to think about both.</p>

<h2 id="levers">The levers that actually move the needle</h2>
<p>Decades of population research point to the same short list. Get these right and you've done the vast majority of
what's in your control:</p>
<ul>
  <li><strong>Don't smoke</strong> — nothing else you do matters as much if you do.</li>
  <li><strong>Move, and keep your muscle.</strong> Regular activity plus strength training is one of the strongest
  predictors of a long, independent life. See our <a href="/guides/muscle-growth">muscle guide</a>.</li>
  <li><strong>Eat mostly whole foods</strong> — plenty of plants, enough protein, not too much ultra-processed food.</li>
  <li><strong>Protect your sleep.</strong> Chronically short sleep works against almost every longevity marker
  (our <a href="/guides/better-sleep">sleep guide</a>).</li>
  <li><strong>Keep alcohol modest</strong> and manage stress.</li>
  <li><strong>Stay socially connected.</strong> Loneliness is a genuine health risk; relationships are a longevity
  factor, not a soft one.</li>
</ul>

<h2 id="supplements">Supplements with a longevity angle</h2>
<p>No pill replaces the levers above, but a few have a reasonable evidence base for healthy ageing: vitamin D
(especially in the UK), omega-3, and creatine (muscle and possibly brain). See our
<a href="/guides/what-supplements-to-take">supplements guide</a>.</p>

<h2 id="nad">NAD+ and cellular ageing</h2>
<p>One of the most active areas in longevity science is <strong>NAD+</strong>, a coenzyme central to energy production
and cellular repair that <strong>declines with age</strong>. Raising NAD+ with precursors has been shown to lift levels
in humans, and research into what that means for healthy ageing is genuinely promising <span class="tier">Promising</span>
— though it's an emerging field, not a proven fountain of youth. Worth understanding honestly rather than over-selling.
Our <a href="/guides/why-am-i-always-tired">energy guide</a> covers the NAD+ story in more depth.</p>

<h2 id="hype">Cutting through the hype</h2>
<p>Longevity marketing is full of miracle molecules and expensive tests. Be sceptical of anything promising to "reverse
ageing" — the evidence for the basics is vastly stronger than for any supplement, and always will be. Do the boring
things brilliantly first.</p>

  
    <aside class="funnel">
      <div class="funnel-k">Where to look</div>
      <p>Interested in the NAD+ and healthy-ageing angle? My Longevity Hub partners with theNAD for its at-home NAD+ kit. Nail the lifestyle basics first — that's where the biggest longevity wins live.</p>
      <a class="funnel-cta" href="https://thenad.co.uk" target="_blank" rel="noopener">Explore theNAD →</a>
    </aside>
  <div class="faqwrap"><h2>Frequently asked questions</h2><div class="faq"><h3>What actually helps you live longer?</h3><p>The strongest levers are not smoking, staying active and keeping muscle, eating mostly whole foods, protecting sleep, keeping alcohol modest, managing stress, and staying socially connected. These matter far more than any supplement.</p></div><div class="faq"><h3>Do longevity supplements work?</h3><p>No supplement replaces the lifestyle basics, but vitamin D, omega-3 and creatine have reasonable evidence for healthy ageing. Be sceptical of anything promising to 'reverse ageing'.</p></div><div class="faq"><h3>Does NAD+ help with ageing?</h3><p>NAD+ is a coenzyme central to energy and repair that declines with age. Precursors can raise NAD+ levels in humans and the healthy-ageing research is promising, but it's an emerging field rather than a proven anti-ageing cure.</p></div></div>
  <div class="refs"><h2>Sources &amp; further reading</h2><ol><li><a href="https://www.nhs.uk/live-well/" target="_blank" rel="noopener nofollow">NHS — Live Well</a></li><li><a href="https://www.hsph.harvard.edu/nutritionsource/healthy-longevity/" target="_blank" rel="noopener nofollow">Harvard T.H. Chan School of Public Health — Healthy longevity</a></li><li><a href="https://health.clevelandclinic.org/how-to-live-longer" target="_blank" rel="noopener nofollow">Cleveland Clinic — How to live longer</a></li><li><a href="https://www.mayoclinic.org/healthy-lifestyle/healthy-aging/basics/healthy-aging/hlv-20049407" target="_blank" rel="noopener nofollow">Mayo Clinic — Healthy ageing</a></li><li><a href="https://examine.com/supplements/creatine/" target="_blank" rel="noopener nofollow">Examine.com — Creatine</a></li></ol></div>
</main>
<footer class="disc">
  <strong>General information only.</strong> This guide is educational and is not medical advice, diagnosis or treatment.
  It doesn't replace a conversation with your GP, pharmacist or a qualified clinician — especially if you're pregnant,
  breastfeeding, taking medication or managing a health condition. For anything urgent, call <strong>999</strong> or NHS <strong>111</strong>.
  Food supplements are not a substitute for a varied diet and a healthy lifestyle.
</footer>`,
} as const;
