// AUTO-GENERATED by scripts/build-guides.mjs — do not edit by hand.
export const guide = {
  slug: "menopause",
  title: "Menopause and Perimenopause: Symptoms, HRT and Real Support",
  lede: "Menopause is a normal life stage — but you don't have to just grit your teeth through it. Here's what's happening, and what genuinely helps.",
  meta: {
    title: "Menopause and Perimenopause: Symptoms, HRT and Real Support | My Longevity Hub",
    description: "A clear, honest guide to menopause and perimenopause — the symptoms, why HRT is the most effective option, the lifestyle that helps, and the supplements with real (and mixed) evidence.",
    keywords: "menopause symptoms, perimenopause, HRT, menopause supplements, hot flushes, menopause and sleep, bone health menopause",
  },
  ldJson: `{"@context": "https://schema.org", "@graph": [{"@type": "Article", "headline": "Menopause and Perimenopause: Symptoms, HRT and Real Support", "description": "A clear, honest guide to menopause and perimenopause \\u2014 the symptoms, why HRT is the most effective option, the lifestyle that helps, and the supplements with real (and mixed) evidence.", "author": {"@type": "Organization", "name": "My Longevity Hub"}, "publisher": {"@type": "Organization", "name": "My Longevity Hub"}, "dateModified": "2026-09-04"}, {"@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": "What are the first signs of perimenopause?", "acceptedAnswer": {"@type": "Answer", "text": "Often irregular periods alongside hot flushes, night sweats, disrupted sleep, mood changes, brain fog and joint aches. It can start in your 40s and last several years as hormone levels fluctuate."}}, {"@type": "Question", "name": "Is HRT safe?", "acceptedAnswer": {"@type": "Answer", "text": "For most women starting it under 60 or within 10 years of menopause, the current consensus is that the benefits outweigh the risks, and it's the most effective treatment for symptoms plus bone protection. It's a personalised decision \\u2014 discuss your history with a GP or menopause specialist."}}, {"@type": "Question", "name": "What supplements help with menopause?", "acceptedAnswer": {"@type": "Answer", "text": "Calcium and vitamin D matter for bone health after menopause; magnesium may help sleep, and omega-3 supports general health. Phytoestrogens and black cohosh help some women with hot flushes but the evidence is mixed \\u2014 check with a clinician first."}}, {"@type": "Question", "name": "When should I see a doctor about menopause?", "acceptedAnswer": {"@type": "Answer", "text": "See your GP if symptoms affect your quality of life, if you'd like to discuss HRT, or for any bleeding after menopause, which should always be checked."}}]}]}`,
  html: `<main>
  <div class="kicker">Guide</div>
  <h1>Menopause and Perimenopause: Symptoms, HRT and Real Support</h1>
  <p class="byline">By the My Longevity Hub editorial team · Updated September 2026 · 3 min read</p>
  <p class="lede">Menopause is a normal life stage — but you don't have to just grit your teeth through it. Here's what's happening, and what genuinely helps.</p>
  
<div class="toc"><div>On this page</div>
  <a href="#whats">What's actually happening</a>
  <a href="#symptoms">Common symptoms</a>
  <a href="#hrt">HRT — the most effective option</a>
  <a href="#lifestyle">Lifestyle that genuinely helps</a>
  <a href="#supplements">Supplements — the honest evidence</a>
  <a href="#doctor">When to see your GP</a>
</div>

<p>Menopause is a normal life stage, not a disease — but that doesn't mean you have to just grit your teeth through it.
There are genuinely effective options, and a lot of unhelpful noise. Here's a clear, honest guide to what's happening
and what actually helps.</p>

<h2 id="whats">What's actually happening</h2>
<p><strong>Perimenopause</strong> is the transition, when hormones (mainly oestrogen) fluctuate — it can start in your
40s and last several years, and periods become irregular. <strong>Menopause</strong> itself is diagnosed after 12
months without a period (on average around age 51 in the UK). After that is <strong>postmenopause</strong>.</p>

<h2 id="symptoms">Common symptoms</h2>
<p>Everyone's experience differs, but common ones include hot flushes and night sweats, disrupted
<a href="/guides/better-sleep">sleep</a>, mood changes and anxiety, brain fog, joint aches, vaginal dryness, changes
in libido, and — importantly for the long term — a faster loss of bone density.</p>

<h2 id="hrt">HRT — the most effective option</h2>
<p>Hormone replacement therapy (HRT) is the <strong>most effective treatment</strong> for menopausal symptoms, and it
also helps protect bone health. The current consensus among UK and international bodies is that <strong>for most women
starting it under 60 or within 10 years of menopause, the benefits outweigh the risks</strong> — the blanket fears from
older headlines have been substantially revised. It isn't right for everyone, so it's a personalised conversation with
your GP or a menopause specialist, who can weigh your own history and options.</p>

<h2 id="lifestyle">Lifestyle that genuinely helps</h2>
<ul>
  <li><strong>Strength and weight-bearing exercise</strong> — protects bone and muscle, and helps mood and sleep.</li>
  <li><strong>Prioritising sleep</strong> and managing stress — both take a hit during this transition.</li>
  <li><strong>Limiting alcohol and caffeine</strong>, which can trigger hot flushes and worsen sleep for some.</li>
  <li><strong>A balanced diet</strong> with enough protein and calcium for muscle and bone.</li>
</ul>

<h2 id="supplements">Supplements — the honest evidence</h2>
<p>Supplements can support the basics but aren't a substitute for medical treatment where that's needed:</p>
<ul>
  <li><strong>Calcium and vitamin D</strong> <span class="tier">Strong (for bone)</span> — important for bone health,
  which matters more after menopause. Vitamin D is worth considering year-round for many in the UK.</li>
  <li><strong>Magnesium</strong> <span class="tier">Promising</span> — may help with sleep and relaxation.</li>
  <li><strong>Omega-3</strong> <span class="tier">Moderate</span> — general heart and health support.</li>
  <li><strong>Phytoestrogens (soy isoflavones) and black cohosh</strong> <span class="tier">Mixed</span> — some women
  find them helpful for hot flushes, but the evidence is inconsistent and they aren't right for everyone (check with a
  clinician first, especially with a history of hormone-sensitive conditions or liver issues).</li>
</ul>

<h2 id="doctor">When to see your GP</h2>
<p>See your GP if symptoms are affecting your quality of life, if you have questions about HRT, or for any unusual
bleeding (for example bleeding after menopause), which should always be checked. Effective help is available — you
don't have to simply endure it.</p>

  
    <aside class="funnel">
      <div class="funnel-k">Where to look</div>
      <p>For everyday support during menopause — vitamin D and calcium for bone health, magnesium for sleep, and omega-3 — imnatura offers UK food supplements. For symptom treatment and HRT, your GP is the place to start.</p>
      <a class="funnel-cta" href="https://imnatura.co.uk" target="_blank" rel="noopener">Browse imnatura supplements →</a>
    </aside>
  <div class="faqwrap"><h2>Frequently asked questions</h2><div class="faq"><h3>What are the first signs of perimenopause?</h3><p>Often irregular periods alongside hot flushes, night sweats, disrupted sleep, mood changes, brain fog and joint aches. It can start in your 40s and last several years as hormone levels fluctuate.</p></div><div class="faq"><h3>Is HRT safe?</h3><p>For most women starting it under 60 or within 10 years of menopause, the current consensus is that the benefits outweigh the risks, and it's the most effective treatment for symptoms plus bone protection. It's a personalised decision — discuss your history with a GP or menopause specialist.</p></div><div class="faq"><h3>What supplements help with menopause?</h3><p>Calcium and vitamin D matter for bone health after menopause; magnesium may help sleep, and omega-3 supports general health. Phytoestrogens and black cohosh help some women with hot flushes but the evidence is mixed — check with a clinician first.</p></div><div class="faq"><h3>When should I see a doctor about menopause?</h3><p>See your GP if symptoms affect your quality of life, if you'd like to discuss HRT, or for any bleeding after menopause, which should always be checked.</p></div></div>
  <div class="refs"><h2>Sources &amp; further reading</h2><ol><li><a href="https://www.nhs.uk/conditions/menopause/" target="_blank" rel="noopener nofollow">NHS — Menopause</a></li><li><a href="https://www.nice.org.uk/guidance/ng23" target="_blank" rel="noopener nofollow">NICE — Menopause: diagnosis and management</a></li><li><a href="https://my.clevelandclinic.org/health/diseases/21841-menopause" target="_blank" rel="noopener nofollow">Cleveland Clinic — Menopause</a></li><li><a href="https://www.mayoclinic.org/diseases-conditions/menopause/diagnosis-treatment/drc-20353401" target="_blank" rel="noopener nofollow">Mayo Clinic — Menopause diagnosis and treatment</a></li><li><a href="https://thebms.org.uk/publications/consensus-statements/" target="_blank" rel="noopener nofollow">British Menopause Society — HRT information</a></li></ol></div>
</main>
<footer class="disc">
  <strong>General information only.</strong> This guide is educational and is not medical advice, diagnosis or treatment.
  It doesn't replace a conversation with your GP, pharmacist or a qualified clinician — especially if you're pregnant,
  breastfeeding, taking medication or managing a health condition. For anything urgent, call <strong>999</strong> or NHS <strong>111</strong>.
  Research peptides referenced here are sold for laboratory research use only and are not for human or animal consumption.
</footer>`,
} as const;
