// AUTO-GENERATED by scripts/build-guides.mjs — do not edit by hand.
export const guide = {
  slug: "muscle-growth",
  title: "Building Muscle and Recovering from Training",
  lede: "Muscle comes down to progressively harder training, enough protein, and real recovery. No supplement or peptide out-runs those three — here's the honest hierarchy.",
  meta: {
    title: "Building Muscle and Recovering from Training | My Longevity Hub",
    description: "An honest guide to building muscle — progressive overload, protein and recovery, the supplements that actually help (creatine), and where growth-hormone peptides like CJC-1295 and Ipamorelin really sit.",
    keywords: "build muscle, muscle recovery, training recovery, protein for muscle, creatine, growth hormone peptides, CJC-1295, Ipamorelin",
  },
  ldJson: `{"@context": "https://schema.org", "@graph": [{"@type": "Article", "headline": "Building Muscle and Recovering from Training", "description": "An honest guide to building muscle \\u2014 progressive overload, protein and recovery, the supplements that actually help (creatine), and where growth-hormone peptides like CJC-1295 and Ipamorelin really sit.", "author": {"@type": "Organization", "name": "My Longevity Hub"}, "publisher": {"@type": "Organization", "name": "My Longevity Hub"}, "dateModified": "2026-09-04"}, {"@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": "What's the best way to build muscle?", "acceptedAnswer": {"@type": "Answer", "text": "Progressive overload in your training, eating enough protein (about 1.6\\u20132.2 g/kg/day), and getting real recovery and sleep \\u2014 applied consistently over months. Everything else is a minor add-on."}}, {"@type": "Question", "name": "Which supplements actually build muscle?", "acceptedAnswer": {"@type": "Answer", "text": "Creatine monohydrate has the strongest evidence and is safe and cheap; protein powder is a convenient way to hit your target; caffeine can help performance. Most other 'muscle' supplements are overhyped."}}, {"@type": "Question", "name": "Do CJC-1295 and Ipamorelin build muscle?", "acceptedAnswer": {"@type": "Answer", "text": "They raise growth hormone in research, but human evidence for real muscle and body-composition benefits is limited, and manipulating growth hormone has unknown long-term effects. They're sold for laboratory research use only and aren't approved for human use."}}, {"@type": "Question", "name": "How much protein do I need to build muscle?", "acceptedAnswer": {"@type": "Answer", "text": "Roughly 1.6\\u20132.2 grams per kilogram of bodyweight per day, spread across meals, is the well-supported range for building muscle alongside progressive training."}}]}]}`,
  html: `<main>
  <div class="kicker">Guide</div>
  <h1>Building Muscle and Recovering from Training</h1>
  <p class="byline">By the My Longevity Hub editorial team · Updated September 2026 · 3 min read</p>
  <p class="lede">Muscle comes down to progressively harder training, enough protein, and real recovery. No supplement or peptide out-runs those three — here's the honest hierarchy.</p>
  
<div class="toc"><div>On this page</div>
  <a href="#foundations">The foundations of building muscle</a>
  <a href="#supplements">Supplements that actually help</a>
  <a href="#peptides">Growth-hormone peptides: the research picture</a>
  <a href="#overhyped">What's overhyped</a>
  <a href="#doctor">Training smart and staying safe</a>
</div>

<p>Building muscle isn't complicated, but it is demanding: it comes down to <strong>progressively harder training,
enough protein, and real recovery</strong>. No supplement or peptide out-runs those three. Here's the honest hierarchy
of what matters — and where the peptides people ask about actually sit.</p>

<h2 id="foundations">The foundations of building muscle</h2>
<ul>
  <li><strong>Progressive overload</strong> — gradually doing more over time (weight, reps, sets) is the core stimulus.</li>
  <li><strong>Enough protein</strong> — roughly 1.6–2.2 g per kg of bodyweight a day, spread across meals, is the
  well-supported range for building muscle.</li>
  <li><strong>Recovery and sleep</strong> — muscle is built between sessions, not during them; protect your
  <a href="/guides/better-sleep">sleep</a> and don't train the same thing into the ground.</li>
  <li><strong>Consistency over months</strong> — the real "secret". Nothing beats showing up.</li>
</ul>

<h2 id="supplements">Supplements that actually help</h2>
<ul>
  <li><strong>Creatine monohydrate</strong> <span class="tier">Strong</span> — the most-proven supplement for strength
  and muscle, safe and inexpensive.</li>
  <li><strong>Protein powder</strong> <span class="tier">Strong (as food)</span> — not magic, just a convenient way to
  hit your protein target.</li>
  <li><strong>Caffeine</strong> <span class="tier">Moderate</span> — can improve training performance.</li>
  <li><strong>Vitamin D</strong> <span class="tier">Moderate</span> — worth not being deficient in for muscle function.</li>
</ul>
<p>See our <a href="/guides/what-supplements-to-take">supplements guide</a> for choosing quality.</p>

<h2 id="peptides">Growth-hormone peptides: the research picture</h2>
<p>Peptides such as <strong>CJC-1295</strong> and <strong>Ipamorelin</strong> are growth-hormone secretagogues — in
research they prompt the body to release more of its own growth hormone. They're a genuine area of study, but the honest
position is that <strong>human evidence for real-world muscle and body-composition benefits is limited</strong>, and
manipulating growth hormone is a hormonal intervention with unknown long-term effects.</p>
<ul>
  <li><strong>CJC-1295 / Ipamorelin</strong> <span class="tier">Limited human data</span> — increase GH/IGF-1 in
  studies; meaningful long-term outcome data in healthy adults is lacking.</li>
</ul>
<div class="callout"><strong>Important:</strong> these are sold <strong>for laboratory research use only</strong> — not
licensed medicines, not approved for human use, and this guide is not advising anyone to take them. Any hormonal
manipulation is a medical matter. The proven foundations above are what actually build muscle.</div>

<h2 id="overhyped">What's overhyped</h2>
<p>BCAAs (if your protein is already adequate), most "test boosters", and elaborate supplement stacks add cost more than
muscle. Fundamentals first, always.</p>

<h2 id="doctor">Training smart and staying safe</h2>
<p>Build load gradually to avoid injury (see our <a href="/guides/injury-recovery">recovery guide</a>), and if you have
a health condition or are new to training, get clearance and ideally coaching to start well.</p>

  
    <aside class="funnel">
      <div class="funnel-k">Where to look</div>
      <p>Growth-hormone peptides like CJC-1295 and Ipamorelin are an active research topic. My Peptides supplies them strictly for laboratory research use only — for those exploring the science, not for personal use. To actually build muscle, the foundations above come first.</p>
      <a class="funnel-cta" href="https://my-peptides.co.uk/products/cjc-1295" target="_blank" rel="noopener">Explore the CJC-1295 research →</a>
    </aside>
  <div class="faqwrap"><h2>Frequently asked questions</h2><div class="faq"><h3>What&#x27;s the best way to build muscle?</h3><p>Progressive overload in your training, eating enough protein (about 1.6–2.2 g/kg/day), and getting real recovery and sleep — applied consistently over months. Everything else is a minor add-on.</p></div><div class="faq"><h3>Which supplements actually build muscle?</h3><p>Creatine monohydrate has the strongest evidence and is safe and cheap; protein powder is a convenient way to hit your target; caffeine can help performance. Most other 'muscle' supplements are overhyped.</p></div><div class="faq"><h3>Do CJC-1295 and Ipamorelin build muscle?</h3><p>They raise growth hormone in research, but human evidence for real muscle and body-composition benefits is limited, and manipulating growth hormone has unknown long-term effects. They're sold for laboratory research use only and aren't approved for human use.</p></div><div class="faq"><h3>How much protein do I need to build muscle?</h3><p>Roughly 1.6–2.2 grams per kilogram of bodyweight per day, spread across meals, is the well-supported range for building muscle alongside progressive training.</p></div></div>
  <div class="refs"><h2>Sources &amp; further reading</h2><ol><li><a href="https://www.nhs.uk/live-well/exercise/" target="_blank" rel="noopener nofollow">NHS — Exercise and physical activity guidelines</a></li><li><a href="https://examine.com/supplements/creatine/" target="_blank" rel="noopener nofollow">Examine.com — Creatine</a></li><li><a href="https://examine.com/nutrition/how-much-protein-do-you-need/" target="_blank" rel="noopener nofollow">Examine.com — How much protein do you need?</a></li><li><a href="https://health.clevelandclinic.org/how-to-build-muscle" target="_blank" rel="noopener nofollow">Cleveland Clinic — Building muscle</a></li><li><a href="https://www.mayoclinic.org/healthy-lifestyle/fitness/in-depth/strength-training/art-20046670" target="_blank" rel="noopener nofollow">Mayo Clinic — Strength training</a></li></ol></div>
</main>
<footer class="disc">
  <strong>General information only.</strong> This guide is educational and is not medical advice, diagnosis or treatment.
  It doesn't replace a conversation with your GP, physiotherapist, pharmacist or a qualified clinician — especially if
  you're pregnant, breastfeeding, taking medication or managing a health condition. For anything urgent, call
  <strong>999</strong> or NHS <strong>111</strong>. Research peptides referenced here are sold for laboratory research
  use only and are not for human or animal consumption.
</footer>`,
} as const;
