// AUTO-GENERATED by scripts/build-guides.mjs — do not edit by hand.
export const guide = {
  slug: "skincare",
  title: "Skincare That Actually Works: An Evidence-Based Guide",
  lede: "A handful of well-evidenced basics do almost all the work for healthy, resilient skin. Here's what genuinely helps — and an honest look at where peptides fit.",
  meta: {
    title: "Skincare That Actually Works: An Evidence-Based Guide | My Longevity Hub",
    description: "An honest, evidence-based skincare guide — the few basics that do most of the work (sunscreen, retinoids), collagen supplements, and where copper peptides (GHK-Cu) fit as research.",
    keywords: "skincare routine, anti-aging skincare, collagen for skin, peptides for skin, GHK-Cu, copper peptides, retinol, best skincare",
  },
  ldJson: `{"@context": "https://schema.org", "@graph": [{"@type": "Article", "headline": "Skincare That Actually Works: An Evidence-Based Guide", "description": "An honest, evidence-based skincare guide \\u2014 the few basics that do most of the work (sunscreen, retinoids), collagen supplements, and where copper peptides (GHK-Cu) fit as research.", "author": {"@type": "Organization", "name": "My Longevity Hub"}, "publisher": {"@type": "Organization", "name": "My Longevity Hub"}, "dateModified": "2026-09-04"}, {"@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": "What's the most important skincare step?", "acceptedAnswer": {"@type": "Answer", "text": "Daily broad-spectrum sunscreen (SPF 30+). UV exposure drives most visible skin ageing, so protecting against it outperforms any serum or cream."}}, {"@type": "Question", "name": "Do collagen supplements work for skin?", "acceptedAnswer": {"@type": "Answer", "text": "There's promising evidence that oral collagen peptides can modestly improve skin elasticity and hydration. They're one of the more defensible beauty supplements, but a good diet and sun protection matter more."}}, {"@type": "Question", "name": "Are copper peptides (GHK-Cu) good for skin?", "acceptedAnswer": {"@type": "Answer", "text": "GHK-Cu has genuine research interest for skin repair and collagen pathways. However, research-grade GHK-Cu sold by peptide suppliers is for laboratory research use only \\u2014 not a cosmetic to apply and not for human use."}}, {"@type": "Question", "name": "Do I need an expensive skincare routine?", "acceptedAnswer": {"@type": "Answer", "text": "No. A simple routine \\u2014 sunscreen, a gentle cleanser and moisturiser, and a retinoid \\u2014 covers the essentials. Most elaborate, pricey routines add cost rather than results."}}]}]}`,
  html: `<main>
  <div class="kicker">Guide</div>
  <h1>Skincare That Actually Works: An Evidence-Based Guide</h1>
  <p class="byline">By the My Longevity Hub editorial team · Updated September 2026 · 3 min read</p>
  <p class="lede">A handful of well-evidenced basics do almost all the work for healthy, resilient skin. Here's what genuinely helps — and an honest look at where peptides fit.</p>
  
<div class="toc"><div>On this page</div>
  <a href="#basics">The proven basics (start here)</a>
  <a href="#collagen">Collagen and skin supplements</a>
  <a href="#peptides">The peptide research frontier</a>
  <a href="#overhyped">What's overhyped</a>
  <a href="#derm">When to see a dermatologist</a>
</div>

<p>Skincare is a huge, noisy market — but the truth is refreshingly boring: a handful of well-evidenced basics do
almost all the work, and everything else is optional polish. Here's what genuinely moves the needle for healthy,
resilient skin as you age, plus an honest look at where peptides fit.</p>

<h2 id="basics">The proven basics (start here)</h2>
<ul>
  <li><strong>Daily sunscreen</strong> <span class="tier">Strong</span> — the single most effective anti-ageing step
  there is. UV drives most visible ageing (lines, pigmentation, laxity). A broad-spectrum SPF 30+ every day beats any
  serum.</li>
  <li><strong>Retinoids (retinol / tretinoin)</strong> <span class="tier">Strong</span> — the gold standard for
  smoothing texture and softening fine lines. Over-the-counter retinol is milder; prescription tretinoin is stronger
  and, in the UK, comes from a doctor. Start low and slow to avoid irritation.</li>
  <li><strong>A gentle routine</strong> <span class="tier">Strong</span> — a mild cleanser and a good moisturiser
  protect the skin barrier. Over-exfoliating and harsh actives do more harm than good.</li>
  <li><strong>Vitamin C</strong> <span class="tier">Moderate</span> — a morning antioxidant serum can help with
  brightness and support collagen.</li>
  <li><strong>Niacinamide</strong> <span class="tier">Moderate</span> — well-tolerated, helps with barrier, redness
  and oil balance.</li>
</ul>
<div class="callout">Lifestyle counts too: not smoking, decent <a href="/guides/better-sleep">sleep</a>, and a balanced
diet all show up on your face over the years.</div>

<h2 id="collagen">Collagen and skin supplements</h2>
<p>Collagen is the scaffolding that keeps skin firm, and it declines with age. Oral <strong>collagen peptides</strong>
<span class="tier">Promising</span> have some evidence for improving skin elasticity and hydration in trials, which
makes them one of the more defensible "beauty" supplements. Vitamin C also supports your own collagen production, and
overall a good diet does more than any single capsule. See our <a href="/guides/what-supplements-to-take">supplements
guide</a> for how to choose well.</p>

<h2 id="peptides">The peptide research frontier</h2>
<p>Peptides are short chains of amino acids that can act as signals in the skin, and they're an active area of research.
The best known is <strong>GHK-Cu (copper peptide)</strong>, which has generated genuine scientific interest for its
role in skin repair, collagen and wound-healing pathways. Some cosmetic peptides (like the "Matrixyl" family) also
appear in topical products.</p>
<div class="callout"><strong>Important:</strong> research-grade GHK-Cu sold by peptide suppliers is <strong>for
laboratory research use only</strong> — not a cosmetic to apply to your skin, and not for human use. If you're
curious about the science, treat it as exactly that: research to read about, not a product to self-experiment with.</div>

<h2 id="overhyped">What's overhyped</h2>
<p>Most 10-step routines, "miracle" creams and expensive essences add cost, not results. If a product promises to
"erase" wrinkles overnight, it can't. Consistency with the basics beats novelty every time.</p>

<h2 id="derm">When to see a dermatologist</h2>
<p>See a professional for persistent acne, rosacea, any new or changing mole, or a skin concern that's affecting your
confidence — prescription options and expert guidance are worth it.</p>

  
    <aside class="funnel">
      <div class="funnel-k">Where to look</div>
      <p>Copper peptides (GHK-Cu) are one of the most interesting areas in skin-repair research. My Peptides supplies research-grade GHK-Cu strictly for laboratory research use only — a resource for those exploring the science, not a product for personal use.</p>
      <a class="funnel-cta" href="https://my-peptides.co.uk/products/ghk-cu" target="_blank" rel="noopener">Explore the GHK-Cu research →</a>
    </aside>
  <div class="faqwrap"><h2>Frequently asked questions</h2><div class="faq"><h3>What&#x27;s the most important skincare step?</h3><p>Daily broad-spectrum sunscreen (SPF 30+). UV exposure drives most visible skin ageing, so protecting against it outperforms any serum or cream.</p></div><div class="faq"><h3>Do collagen supplements work for skin?</h3><p>There's promising evidence that oral collagen peptides can modestly improve skin elasticity and hydration. They're one of the more defensible beauty supplements, but a good diet and sun protection matter more.</p></div><div class="faq"><h3>Are copper peptides (GHK-Cu) good for skin?</h3><p>GHK-Cu has genuine research interest for skin repair and collagen pathways. However, research-grade GHK-Cu sold by peptide suppliers is for laboratory research use only — not a cosmetic to apply and not for human use.</p></div><div class="faq"><h3>Do I need an expensive skincare routine?</h3><p>No. A simple routine — sunscreen, a gentle cleanser and moisturiser, and a retinoid — covers the essentials. Most elaborate, pricey routines add cost rather than results.</p></div></div>
  <div class="refs"><h2>Sources &amp; further reading</h2><ol><li><a href="https://www.nhs.uk/live-well/seasonal-health/sunscreen-and-sun-safety/" target="_blank" rel="noopener nofollow">NHS — Sunscreen and sun safety</a></li><li><a href="https://www.aad.org/public/everyday-care/skin-care-basics" target="_blank" rel="noopener nofollow">American Academy of Dermatology — Skin care basics</a></li><li><a href="https://health.clevelandclinic.org/do-collagen-supplements-work" target="_blank" rel="noopener nofollow">Cleveland Clinic — Do collagen supplements work?</a></li><li><a href="https://www.mayoclinic.org/diseases-conditions/wrinkles/in-depth/wrinkle-creams/art-20047463" target="_blank" rel="noopener nofollow">Mayo Clinic — Wrinkle creams: your guide to younger looking skin</a></li><li><a href="https://examine.com/supplements/collagen/" target="_blank" rel="noopener nofollow">Examine.com — Collagen</a></li></ol></div>
</main>
<footer class="disc">
  <strong>General information only.</strong> This guide is educational and is not medical advice, diagnosis or treatment.
  It doesn't replace a conversation with your GP, pharmacist or a qualified clinician — especially if you're pregnant,
  breastfeeding, taking medication or managing a health condition. For anything urgent, call <strong>999</strong> or NHS <strong>111</strong>.
  Research peptides referenced here are sold for laboratory research use only and are not for human or animal consumption.
</footer>`,
} as const;
