import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));            // frontend/scripts
const SRC_DIR = join(HERE, "..", "..", "backend", "app", "static", "guides");
const OUT_DIR = join(HERE, "..", "content", "guides");

// Canonical order — matches backend/app/guides.py GUIDES.
export const SLUGS = [
  "better-sleep", "why-am-i-always-tired", "what-supplements-to-take", "skincare",
  "hair-loss", "testosterone", "menopause", "injury-recovery", "muscle-growth",
  "gut-health", "peptides-101", "longevity-basics", "weight-loss", "stress-focus", "immunity",
];

function decodeEntities(s) {
  return (s || "")
    .replace(/&#x27;/gi, "'").replace(/&#39;/g, "'")
    .replace(/&#x2014;/gi, "—").replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"').replace(/&lt;/g, "<").replace(/&gt;/g, ">")
    .replace(/\s+/g, " ").trim();
}

function pick(re, raw) { const m = raw.match(re); return m ? m[1] : ""; }
function stripTags(s) { return decodeEntities((s || "").replace(/<[^>]*>/g, "")); }

export function extractGuide(raw) {
  const title = decodeEntities(pick(/<title>([\s\S]*?)<\/title>/i, raw));
  const description = decodeEntities(pick(/<meta name="description" content="([\s\S]*?)">/i, raw));
  const keywords = decodeEntities(pick(/<meta name="keywords" content="([\s\S]*?)">/i, raw));
  const ldJson = pick(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/i, raw).trim();
  const h1 = stripTags(pick(/<h1[^>]*>([\s\S]*?)<\/h1>/i, raw));
  const lede = stripTags(pick(/<p class="lede">([\s\S]*?)<\/p>/i, raw));
  // Body region: <main> … </main> plus an optional trailing <footer class="disc"> … </footer>.
  const html = pick(/(<main[\s\S]*?<\/main>(?:\s*<footer[\s\S]*?<\/footer>)?)/i, raw).trim();
  return { title, description, keywords, h1, lede, ldJson, html };
}

// Escape a string for embedding inside a TS template literal.
function esc(s) { return String(s).replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${"); }

function moduleSource(slug, g) {
  return `// AUTO-GENERATED by scripts/build-guides.mjs — do not edit by hand.
export const guide = {
  slug: ${JSON.stringify(slug)},
  title: ${JSON.stringify(g.h1 || g.title)},
  lede: ${JSON.stringify(g.lede)},
  meta: {
    title: ${JSON.stringify(g.title)},
    description: ${JSON.stringify(g.description)},
    keywords: ${JSON.stringify(g.keywords)},
  },
  ldJson: \`${esc(g.ldJson)}\`,
  html: \`${esc(g.html)}\`,
} as const;
`;
}

function main() {
  mkdirSync(OUT_DIR, { recursive: true });
  const catalog = [];
  for (const slug of SLUGS) {
    const raw = readFileSync(join(SRC_DIR, `${slug}.html`), "utf8");
    const g = extractGuide(raw);
    if (!g.html) throw new Error(`No <main> extracted for ${slug}`);
    writeFileSync(join(OUT_DIR, `${slug}.ts`), moduleSource(slug, g));
    catalog.push({ slug, title: g.h1 || g.title, subtitle: "My Longevity Hub guide", lede: g.lede });
  }
  // index.ts — static registry (server-only; imports the heavy modules)
  const imports = SLUGS.map((s, i) => `import { guide as g${i} } from "./${s}";`).join("\n");
  const arr = SLUGS.map((_, i) => `g${i}`).join(", ");
  writeFileSync(join(OUT_DIR, "index.ts"),
`// AUTO-GENERATED by scripts/build-guides.mjs — do not edit by hand.
${imports}

export const GUIDES = [${arr}] as const;
export type Guide = (typeof GUIDES)[number];
export const BY_SLUG: Record<string, Guide> =
  Object.fromEntries(GUIDES.map((g) => [g.slug, g]));
`);
  // catalog.ts — lightweight, client-safe (no html blobs)
  writeFileSync(join(OUT_DIR, "catalog.ts"),
`// AUTO-GENERATED by scripts/build-guides.mjs — do not edit by hand.
export interface GuideCatalogEntry { slug: string; title: string; subtitle: string; lede: string; }
export const GUIDE_CATALOG: GuideCatalogEntry[] = ${JSON.stringify(catalog, null, 2)};
const TITLES: Record<string, string> = Object.fromEntries(GUIDE_CATALOG.map((g) => [g.slug, g.title]));
export function guideTitle(slug: string): string | undefined { return TITLES[slug]; }
`);
  console.log(`Wrote ${SLUGS.length} guides + index + catalog to ${OUT_DIR}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
